---
- name: Install Progress
  yum:
    name: postgresql-server
    state: latest

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "/usr/share/pgsql"
  register: pg_data_check

- name: Initilize Postgres database
  command: postgresql-setup initdb
  when: not pg_data_check.stat.exists

- name: Start Postgres and enable at boot
  service:
    name: postgresql
    enabled: yes
    state: started
