---
- name: Install Windows AD Domain Services feature
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Setup AD Controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: ad_configuration

- name: Reboot after AD configuration 
  win_reboot:
  when: ad_configuration.reboot_required

- name: List DCs in domain
  win_shell: "nltest /dclist:{{ ad_domain_name }}"
  register: domain_list

- debug:
     var: domain_list
