---
# tasks file for osp-facts

- name: get openstack instance info
  os_server_facts:
    cloud: ospcloud
    region_name: RegionOne
  register: result

- debug:
        msg: "Server Name: {{ item.name }}, Public IP: {{ item.public_v4 }}, Private IP: {{ item.private_v4 }}, Group: {{ item.metadata.group }}, Deployment {{ item.metadata.deployment }}"
  loop: "{{ result.ansible_facts.openstack_servers }}"

- name: add hosts to in memory inventory
  add_host:
    name: "{{ item.name }}"
    ansible_ssh_host: "{{ item.public_v4 }}"
    groups: "{{ item.metadata.group }}, {{ item.metadata.deployment }}"
  loop: "{{ result.ansible_facts.openstack_servers }}"

