- hosts: jumpbox

  tasks:
  - name: get openstack instance info
    os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
    register: result

  - name: debug
    debug:
      msg: "Debug output: {{ result }}"
