---
# 
- name: Install Tomcat
  package:
    name: tomcat
    state: latest

- name: Create Tomcat ansible directory
  file:
    path: "{{ tomcat_root }}"
    state: directory

- name: copy static index.html to tomcat root
  template:
    src: index.html.j2
    dest: "{{ tomcat_root }}/index.html"
    mode: 0644

- name: Start Tomcat and enable at boot
  service:
    name: tomcat
    enabled: yes
    state: started
